
spring:
  datasource:
    url: jdbc:mysql://boyce.top:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: default
    # 开发时显示 sql，部署到生产环境时设为 false
    show-sql: true
    # 使用 mysql 方言
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      # 下面两个配置对应 hibernate 的属性
      ddl-auto: update
    properties:
      hibernate:
        # 格式化 sql 语句
        format_sql: true
    open-in-view: false

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: boyce.top
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: redispass
    lettuce.pool:
      # 连接池最大连接数（使用负值表示没有限制） 默认 8
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
      max-wait: -1
      # 连接池中的最大空闲连接 默认 8
      max-idle: 8
      # 连接池中的最小空闲连接 默认 0
      min-idle: 0
server:
  port: 8081