spring:
  profiles:
    active: dev  # TODO:test的H2数据库启动报错

  # 是否生成ddl语句
  jpa:
    generate-ddl: false
  # 是否打印sql语句
    show-sql: true
  # 自动生成ddl，由于指定了具体的ddl，此处设置为none
    hibernate:
      ddl-auto: none

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: dev.host
    # Redis服务器连接端口
    port: 6379
    lettuce.pool:
      # 连接池最大连接数（使用负值表示没有限制） 默认 8
      maxActive: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
      maxWait: -1
      # 连接池中的最大空闲连接 默认 8
      maxIdle: 8
      # 连接池中的最小空闲连接 默认 0
      minIdle: 0
server:
  port: 8081